classes:
- system.salt.master.pkg
- system.salt.master.api
- system.openssh.server.single
- system.reclass.storage.salt
parameters:
  _param:
    cluster_domain: ${_param:cluster_name}.${_param:domain}
    linux_system_codename: xenial
    reclass_data_repository: 
    reclass_data_revision: master
    linux_repo_refresh_db: true
    salt_master_base_environment: prd
    salt_api_password_hash: "$6$sDHRYFYZ$cFRDr/jshAF/oT9uMAfV7vPTANQkna7ff83SoiD4XQaXRz1v2EYpr8pXVa81ZrBGB6XnpEhK5kwbPQHBekm3o/"
    salt_api_password: vyaPRQXnMsLCKCSlsTind9td59bCB8iR
    salt_master_ip: 172.13.0.10
    oc_address:     172.13.0.11
    ctl_address:    172.13.0.13
    cmp_network:    172.13.0
    cmp_count: 2
  reclass:
    storage:
      data_source:
        engine: local
      node:
        oc_node:
          name: ${_param:cluster_name}oc
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.common.infra.salt-minion
          - cluster.common.opencontrail.repo
          - cluster.common.opencontrail.docker
          - cluster.${_param:cluster_name}.opencontrail.override
          params:
            single_address: ${_param:oc_address}
            salt_master_host: ${_param:salt_master_ip}
            cluster_name: ${_param:cluster_name}
            cluster_domain: ${_param:cluster_name}.${_param:domain}
            openstack_control_address: ${_param:ctl_address}
        ctl_node:
          name: ${_param:cluster_name}ctl
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.common.infra.salt-minion
          - cluster.common.openstack.repo
          - cluster.common.openstack.mysql
          - cluster.common.openstack.rabbitmq
          - cluster.common.openstack.keystone
          - cluster.common.openstack.glance
          - cluster.common.openstack.horizon
          - cluster.common.openstack.nova
          - cluster.${_param:cluster_name}.openstack.neutron
          - cluster.${_param:cluster_name}.openstack.override
          params:
            single_address: ${_param:ctl_address}
            salt_master_host: ${_param:salt_master_ip}
            cluster_name: ${_param:cluster_name}
            cluster_domain: ${_param:domain}
            openstack_proxy_address: ${_param:ctl_address}
        cmp_node:
          name: ${_param:cluster_name}cmp<<count>>
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.common.infra.salt-minion
          - cluster.common.openstack.repo
          repeat:
            count: ${_param:cmp_count}
            start: 0
            digits: 1
            params:
              single_address:
                value: ${_param:cmp_network}.<<count>>
                start: 100
          params:
            salt_master_host: ${_param:salt_master_ip}
            cluster_name: ${_param:cluster_name}
            cluster_domain: ${_param:domain}
            openstack_proxy_address: ${_param:ctl_address}
  linux:
    system:
      enabled: true
  salt:
    master:
     base_environment: prd
