classes:
- system.salt.master.pkg
- system.salt.master.api
- system.openssh.server.single
- system.reclass.storage.salt
parameters:
  _param:
    linux_system_codename: xenial
    reclass_data_repository: 
    reclass_data_revision: master
    linux_repo_refresh_db: true
    salt_master_base_environment: prd
    salt_api_password_hash: "$6$sDHRYFYZ$cFRDr/jshAF/oT9uMAfV7vPTANQkna7ff83SoiD4XQaXRz1v2EYpr8pXVa81ZrBGB6XnpEhK5kwbPQHBekm3o/"
    salt_api_password: vyaPRQXnMsLCKCSlsTind9td59bCB8iR
    salt_master_ip: 192.168.0.10
    aio_address: 192.168.0.11
    mon_address: 192.168.0.12
    cid_address: 192.168.0.13
  reclass:
    storage:
      data_source:
        engine: local
      node:
        aio_node:
          name: ${_param:stack_name}aio
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.infra.telegraf
          - cluster.${_param:stack_name}.openstackaio.repo
          - cluster.${_param:stack_name}.openstackaio.mysql
          - cluster.${_param:stack_name}.openstackaio.rabbitmq
          - cluster.${_param:stack_name}.openstackaio.keystone
          - cluster.${_param:stack_name}.openstackaio.glance
          - cluster.${_param:stack_name}.openstackaio.nova
          - cluster.${_param:stack_name}.openstackaio.neutron
          - cluster.${_param:stack_name}.openstackaio.horizon
          - cluster.${_param:stack_name}.openstackaio.override
          params:
            single_address: ${_param:aio_address}
            salt_master_host: ${_param:salt_master_ip}
            cluster_name: ${_param:stack_name}
            cluster_domain: ${_param:stack_name}.${_param:domain}
        mon_node:
          name: ${_param:stack_name}mon
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.infra.telegraf
          - cluster.${_param:stack_name}.stacklight.repo
          - cluster.${_param:stack_name}.stacklight.glusterfs_single
          - cluster.${_param:stack_name}.stacklight.glusterfs
          - cluster.${_param:stack_name}.stacklight.docker
          - cluster.${_param:stack_name}.stacklight.haproxy_single
          - cluster.${_param:stack_name}.stacklight.haproxy
          - cluster.${_param:stack_name}.stacklight.grafana
          - cluster.${_param:stack_name}.stacklight.monitoring
          - cluster.${_param:stack_name}.stacklight.janitor_monkey
          - cluster.${_param:stack_name}.stacklight.postgresql
          - cluster.${_param:stack_name}.stacklight.pushkin
          - cluster.${_param:stack_name}.stacklight.rundeck
          - cluster.${_param:stack_name}.stacklight.security_monkey
          - cluster.${_param:stack_name}.stacklight.devops_portal
          - cluster.${_param:stack_name}.stacklight.override
          params:
            single_address: ${_param:mon_address}
            salt_master_host: ${_param:salt_master_ip}
            cluster_name: ${_param:stack_name}
            cluster_domain: ${_param:stack_name}.${_param:domain}
            cid_host: ${_param:cid_address}
        cid_node:
          name: ${_param:stack_name}cid
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.infra.telegraf
          - cluster.${_param:stack_name}.drivetrain.repo
          - cluster.${_param:stack_name}.drivetrain.glusterfs_single
          - cluster.${_param:stack_name}.drivetrain.glusterfs
          - cluster.${_param:stack_name}.drivetrain.docker
          - cluster.${_param:stack_name}.drivetrain.haproxy_single
          - cluster.${_param:stack_name}.drivetrain.haproxy
          - cluster.${_param:stack_name}.drivetrain.openldap
          - cluster.${_param:stack_name}.drivetrain.gerrit
          - cluster.${_param:stack_name}.drivetrain.jenkins_single
          - cluster.${_param:stack_name}.drivetrain.jenkins
          - cluster.${_param:stack_name}.drivetrain.kqueen
          - cluster.${_param:stack_name}.drivetrain.override
          params:
            single_address: ${_param:cid_address}
            salt_master_host: ${_param:salt_master_ip}
            cluster_domain: ${_param:stack_name}.${_param:domain}
            cluster_name: ${_param:stack_name}
            salt_api_password: ${_param:salt_api_password}
  linux:
    system:
      enabled: true
  salt:
    master:
     base_environment: prd
