classes:
- system.salt.master.pkg
- system.openssh.server.single
- system.reclass.storage.salt
parameters:
  _param:
    linux_system_codename: xenial
    reclass_data_repository: 
    reclass_data_revision: master
    linux_repo_refresh_db: true
    salt_master_base_environment: prd
    salt_master_host: 192.168.0.10
    aio_address: 192.168.0.11
    mon_address: 192.168.0.12
    cid_address: 192.168.0.13
  reclass:
    storage:
      data_source:
        engine: local
      node:
        aio_node:
          name: ${_param:stack_name}aio
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.openstackaio.repo
          - cluster.${_param:stack_name}.openstackaio.mysql
          - cluster.${_param:stack_name}.openstackaio.rabbitmq
          - cluster.${_param:stack_name}.openstackaio.keystone
          - cluster.${_param:stack_name}.openstackaio.glance
          - cluster.${_param:stack_name}.openstackaio.nova
          - cluster.${_param:stack_name}.openstackaio.neutron
          - cluster.${_param:stack_name}.openstackaio.horizon
          - cluster.${_param:stack_name}.openstackaio.override
          params:
            single_address: ${_param:aio_address}
            salt_master_host: ${_param:salt_master_host}
        mon_node:
          name: ${_param:stack_name}mon
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.stacklight.repo
          - cluster.${_param:stack_name}.stacklight.glusterfs_single
          - cluster.${_param:stack_name}.stacklight.glusterfs
          - cluster.${_param:stack_name}.stacklight.docker
          - cluster.${_param:stack_name}.stacklight.haproxy_single
          - cluster.${_param:stack_name}.stacklight.haproxy
          - cluster.${_param:stack_name}.stacklight.grafana
          - cluster.${_param:stack_name}.stacklight.influxdb
          - cluster.${_param:stack_name}.stacklight.monitoring
          - cluster.${_param:stack_name}.stacklight.elasticsearch
          - cluster.${_param:stack_name}.stacklight.janitor_monkey
          - cluster.${_param:stack_name}.stacklight.postgresql
          - cluster.${_param:stack_name}.stacklight.pushkin
          - cluster.${_param:stack_name}.stacklight.rundeck
          - cluster.${_param:stack_name}.stacklight.security_monkey
          - cluster.${_param:stack_name}.stacklight.devops_portal
          - cluster.${_param:stack_name}.stacklight.override
          params:
            single_address: ${_param:mon_address}
            salt_master_host: ${_param:salt_master_host}
        cid_node:
          name: ${_param:stack_name}cid
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.infra.salt-minion
          - cluster.${_param:stack_name}.drivetrain.repo
          - cluster.${_param:stack_name}.drivetrain.glusterfs_single
          - cluster.${_param:stack_name}.drivetrain.glusterfs
          - cluster.${_param:stack_name}.drivetrain.docker
          - cluster.${_param:stack_name}.drivetrain.haproxy_single
          - cluster.${_param:stack_name}.drivetrain.haproxy
          - cluster.${_param:stack_name}.drivetrain.openldap
          - cluster.${_param:stack_name}.drivetrain.gerrit
          - cluster.${_param:stack_name}.drivetrain.jenkins_single
          - cluster.${_param:stack_name}.drivetrain.jenkins
          - cluster.${_param:stack_name}.drivetrain.override
          params:
            single_address: ${_param:cid_address}
            salt_master_host: ${_param:salt_master_host}
  linux:
    system:
      enabled: true
  salt:
    master:
     base_environment: prd
