classes:
- system.linux.system.repo.mcp.salt
- system.salt.master.pkg
- system.salt.minion.master
- system.openssh.server.single
- system.reclass.storage.salt
parameters:
  _param:
    linux_system_codename: xenial
    reclass_data_repository: 
    reclass_data_revision: master
    linux_repo_refresh_db: true
    salt_master_base_environment: prd
  reclass:
    storage:
      data_source:
        engine: local
      node:
        mon_node:
          name: ${_param:stack_name}mon
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.stacklight
          params:
            deploy_address: 192.168.0.11
        aio_node:
          name: ${_param:stack_name}aio
          domain: ${_param:domain}
          environment: ${_param:salt_master_base_environment}
          classes:
          - cluster.${_param:stack_name}.openstackaio
          params:
            deploy_address: 192.168.0.12
  linux:
    system:
      enabled: true
    storage:
      enabled: true
  salt:
    master:
     base_environment: prd
